### ISSUE TITLE
Error loading STL file

### ISSUE THREAD

**Issue by nicoguaro** [precise-simulation/mesh-viewer#1]
I tried to load an STL [chess knight](https://github.com/nicoguaro/3D_models/blob/master/chess/STL%20files/knight.STL) but it throws the following error:

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "meshviewer.py", line 274, in open
    self.model.load_file(file_name)
  File "meshviewer.py", line 46, in load_file
    self.data.append(mesh)
UnboundLocalError: local variable 'mesh' referenced before assignment
````

**Comment by precise-simulation** [comment]
The chess knight is in binary STL format while the basic **load_stl** function implementation just parses ASCII. You can quite easily add the [numpy-stl](https://github.com/WoLpH/numpy-stl) library which also supports binary STL format. Please look at the corresponding example in the corresponding [readme](https://github.com/WoLpH/numpy-stl/blob/develop/README.rst).

**Comment by nicoguaro** [comment]
Thanks for your reply. I think that adding that it works only for ASCII files in the README would help.
